name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B clean package -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn -B test

  quality-check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  containerization:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: containerization
    steps:
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

  monitor:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Setup Monitoring
        run: echo "Setup monitoring tools or scripts"
